name: Build Linux

on:
  workflow_call:
    inputs:
      run_tests:
        description: Build and run tests
        required: false
        type: boolean
        default: false

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout workspace
        uses: actions/checkout@v6

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          host: 'linux'
          target: 'desktop'
          arch: 'linux_gcc_64'
          cache: true

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake git wget

      - name: Clone repositories
        run: |
          cmake -DREDASM_FETCH_TESTS=${{ inputs.run_tests && 'ON' || 'OFF' }} \
                -DREDASM_SHALLOW=ON  \
                -P Setup.cmake

      - name: Configure
        run: |
          cmake -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=/usr ${{ inputs.run_tests && format('-DREDASM_SAMPLES={0}/samples', github.workspace) || '' }}

      - name: Build
        run: cmake --build build --parallel

      - name: Run tests
        if: inputs.run_tests
        shell: bash
        run: ctest --test-dir build --output-on-failure

      - name: Install into AppDir
        run: cmake --install build --prefix AppDir/usr

      - name: Download linuxdeploy
        run: |
          wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget -q https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy-x86_64.AppImage linuxdeploy-plugin-qt-x86_64.AppImage

      - name: Build AppImage
        env:
          QMAKE: qmake6
        run: |
          ./linuxdeploy-x86_64.AppImage \
            --appdir AppDir \
            --plugin qt \
            --output appimage

      - name: Rename AppImage
        run: mv REDasm-x86_64.AppImage REDasm-linux-x86_64.AppImage

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: REDasm-linux-x86_64
          path: REDasm-linux-x86_64.AppImage
          retention-days: 7
