name: Build Windows

on:
  workflow_call:
    inputs:
      run_tests:
        description: Build and run test suite
        required: false
        type: boolean
        default: false
      version:
        description: Pin components to a specific Git ref (defaults to master).
        required: false
        type: string
        default: ''

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout workspace
        uses: actions/checkout@v6

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          cache: true

      - name: Clone repositories
        run: |
          cmake -DREDASM_FETCH_TESTS=${{ inputs.run_tests && 'ON' || 'OFF' }} `
                -DREDASM_SHALLOW=ON `
                ${{ inputs.version != '' && format('-DREDASM_VERSION_DEFAULT="{0}"', inputs.version) || '' }} `
                -P Setup.cmake

      - name: Configure
        run: |
          cmake -B build `
                -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}" `
                ${{ inputs.version != '' && format('-DREDASM_RELEASE_TAG="{0}"', inputs.version) || '' }} `
                ${{ inputs.run_tests && format('-DREDASM_SAMPLES="{0}/samples"', github.workspace) || '' }}

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Add DLL to PATH
        if: inputs.run_tests
        shell: pwsh
        run: echo "$(pwd)/build/redasm/Release" >> $env:GITHUB_PATH

      - name: Run tests
        if: inputs.run_tests
        shell: pwsh
        run: ctest --test-dir build -C Release --output-on-failure

      - name: Install
        run: cmake --install build --prefix redasm-windows-x86_64 --config Release

      - name: Deploy Qt dependencies
        run: windeployqt --no-translations redasm-windows-x86_64/redasm-gui.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: REDasm-windows-x86_64
          path: redasm-windows-x86_64/
          retention-days: 7
