name: CI

on:
  repository_dispatch:
    types: [ repo_updated ]
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ci
  cancel-in-progress: true

jobs:
  build-linux:
    uses: ./.github/workflows/build-linux.yml

  build-windows:
    uses: ./.github/workflows/build-windows.yml
